# general settings
name: train_SR_CyGen_0002
save_path: C:/MyCode/code for BS/SR-CyGen/SR-CyGen/expm
load_path: ~
random_seed: 99
gpu: 0
batch_size: 1

# dataset and data loader settings
datasets:
  train:
    name: MyDataSet-ITCVD
    dataroot: C:/MyDocuments/Dataset_SR/cheatset

    use_hflip: true
    use_vflip: true
    use_rot: false

    # data loader
    use_shuffle: true

  valid:
    name: MyDataSet-ITCVD
    dataroot: C:/MyDocuments/Dataset_SR/cheatset

# network structures
network:
  dim_z: 128
  n_RRDB: 4
  w_mse: 1.
  w_cm_1: 0.1
  w_cm_2: 0.1
  cmtype: jacnorm_x
  pxtype: nllhmarg

# training settings
train:
  ema_decay: 0.999
  type: Adamax
  lr: !!float 2e-4
  lr_resDecoder: !!float 2e-4
  weight_decay: 0

  scheduler:
    type: StepLR
    step_size: 1
    gamma: 0.99

  total_epoch: 100
  warm_up: 10


# validation settings
val:
  save_img: true
  save_batch_num: 5


# logging settings
logger:
  print_freq: 100
  use_tb_logger: false
  save_img_per_val: 16
  wandb:
    project: ~
    resume_id: ~

